version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.receipt.rule=Host(`receipt.image-description-generator.site`)
      - traefik.http.routers.receipt.entrypoints=websecure
      - traefik.http.routers.receipt.tls=true
      - traefik.http.routers.receipt.tls.certresolver=myresolver
    volumes:
      - prisma-data:/app/prisma
    restart: unless-stopped


volumes:
  prisma-data:
